[package]
name = "dotium"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
async-trait = "0"
thiserror = "1"